#!/usr/bin/env bash
# Install the prompt skills into coding-agent skill directories.
#
# Each skill is installed as a SELF-CONTAINED unit. The skill's own files are
# copied under <target>/skills/<name>/, and the shared resources that skill
# actually references (shared/reference/*.md and, if any script is used, the
# whole shared/scripts/ set) are copied into <target>/skills/<name>/shared/.
# So a skill directory carries everything it needs and can be registered or
# moved on its own (GitHub Copilot, opencode, Claude Code; OpenAI Codex via
# --codex-config). No top-level shared/ tree is created.
#
# Every shared/ reference in the installed skill (with or without a leading
# ../../) is rewritten to an ABSOLUTE path under that skill's own shared/, so
# it resolves regardless of the agent's working directory. Absolute paths are
# deliberate: weak models resolve them reliably where a relative path is
# ambiguous.
#
# With --with-parent, the prebuilt AGENTS.md and CLAUDE.md (generated by
# build.py from the shared invariants) are copied into each target root so the
# <honesty_contract> / <language_policy> / <work_discipline> the skills assume
# are actually present.
#
# Usage: skills.sh [--target DIR]... [--with-parent] [--dry-run] [--codex-config]
#   --target DIR     target root (repeatable; default ~/.agents and ~/.claude)
#   --with-parent    also install AGENTS.md + CLAUDE.md into each target root
#   --dry-run        print actions without writing
#   --codex-config   print the [[skills.config]] block for ~/.codex/config.toml
#
# bootstrap/install.sh delegates here for the "LLM agent skills" component; this
# script is also runnable on its own.
set -euo pipefail

# This script lives at <repo>/bootstrap/. The agents subsystem (skills, shared/,
# and the generated parent files in dist/) is the sibling <repo>/agents/.
SRC="$(cd "$(dirname "$0")/../agents" && pwd)"

expand_tilde() {
  # Expand a literal leading ~ (only reached when --target is quoted, since the
  # shell expands ~ before the script otherwise). The ~ is stripped literally,
  # not tilde-expanded; SC2088 is a false positive here.
  # shellcheck disable=SC2088
  case "$1" in
    "~") printf '%s' "$HOME" ;;
    "~/"*) printf '%s/%s' "$HOME" "${1#"~/"}" ;;
    *) printf '%s' "$1" ;;
  esac
}

targets=()
dry_run=0
codex_config=0
with_parent=0
while [ "$#" -gt 0 ]; do
  case "$1" in
    --target)
      targets+=("$2")
      shift 2
      ;;
    --with-parent)
      with_parent=1
      shift
      ;;
    --dry-run)
      dry_run=1
      shift
      ;;
    --codex-config)
      codex_config=1
      shift
      ;;
    -h | --help)
      sed -n '2,20p' "$0"
      exit 0
      ;;
    *)
      echo "unknown option: $1" >&2
      exit 2
      ;;
  esac
done
if [ "${#targets[@]}" -eq 0 ]; then
  targets=("$HOME/.agents" "$HOME/.claude")
fi

if [ ! -d "$SRC/skills" ] || [ ! -d "$SRC/shared" ]; then
  echo "error: expected $SRC/skills and $SRC/shared" >&2
  exit 1
fi

skill_arr=()
for d in "$SRC"/skills/*/; do
  [ -f "${d}SKILL.md" ] && skill_arr+=("$(basename "$d")")
done

# Copy a tree, excluding test/build cruft, from $1 into $2 (which is created).
copy_tree() {
  mkdir -p "$2"
  tar -C "$1" \
    --exclude='__pycache__' --exclude='*.pyc' \
    --exclude='.pytest_cache' --exclude='tests' \
    -cf - . | tar -C "$2" -xf -
}

install_skill() {
  local name="$1" abs="$2"
  local src="$SRC/skills/$name"
  local dest="$abs/skills/$name"
  copy_tree "$src" "$dest"

  # Decide which shared resources this skill needs, by scanning its markdown.
  local need_scripts=0 need_all_refs=0
  local ref_files=()
  if grep -rq 'shared/scripts/' "$dest"; then
    need_scripts=1
  fi
  # A placeholder reference (e.g. shared/reference/<language>.md) means the
  # skill picks the file at runtime, so it needs the whole reference set.
  if grep -rq 'shared/reference/<' "$dest"; then
    need_all_refs=1
  fi
  # Concrete .md references: collect the exact files (deduplicated).
  while IFS= read -r fname; do
    [ -n "$fname" ] && ref_files+=("$fname")
  done < <(grep -rhoE 'shared/reference/[A-Za-z0-9_-]+\.md' "$dest" |
    sed 's#shared/reference/##' | sort -u)

  # Copy the referenced shared/reference files (or all, for placeholders).
  if [ "$need_all_refs" -eq 1 ]; then
    mkdir -p "$dest/shared/reference"
    cp "$SRC"/shared/reference/*.md "$dest/shared/reference/"
  elif [ "${#ref_files[@]}" -gt 0 ]; then
    mkdir -p "$dest/shared/reference"
    for rf in "${ref_files[@]}"; do
      [ -f "$SRC/shared/reference/$rf" ] && cp "$SRC/shared/reference/$rf" "$dest/shared/reference/$rf"
    done
  fi
  # Scripts have internal dependencies (_common.py), so copy them as a set.
  if [ "$need_scripts" -eq 1 ]; then
    copy_tree "$SRC/shared/scripts" "$dest/shared/scripts"
  fi

  # Rewrite every shared/ reference to an absolute path under this skill.
  # Escape the sed-special characters (#, &, backslash) in the destination path
  # so a target dir containing them does not break or corrupt the substitution.
  local rewritten=0 f esc_dest
  esc_dest=$(printf '%s' "$dest" | sed 's/[#&\\]/\\&/g')
  while IFS= read -r f; do
    sed -E "s#(\.\./)*shared/(reference|scripts)/#${esc_dest}/shared/\2/#g" "$f" >"$f.tmp"
    cmp -s "$f" "$f.tmp" || rewritten=$((rewritten + 1))
    mv "$f.tmp" "$f"
  done < <(find "$dest" -name '*.md')
  echo "  $name (rewrote $rewritten md files)"
}

for t in "${targets[@]}"; do
  t="$(expand_tilde "$t")"
  if [ "$dry_run" -eq 1 ]; then
    echo "[dry-run] would install self-contained skills -> $t/skills/<name>/"
    echo "[dry-run]   skills: ${skill_arr[*]}"
    echo "[dry-run]   each gets only the shared/ refs it uses, rewritten to absolute"
    [ "$with_parent" -eq 1 ] && echo "[dry-run]   plus AGENTS.md + CLAUDE.md -> $t/"
    continue
  fi
  mkdir -p "$t"
  abs="$(cd "$t" && pwd)"
  echo "installing -> $abs"
  for name in "${skill_arr[@]}"; do
    install_skill "$name" "$abs"
  done
  if [ "$with_parent" -eq 1 ]; then
    if [ -f "$SRC/dist/AGENTS.md" ] && [ -f "$SRC/dist/CLAUDE.md" ]; then
      cp "$SRC/dist/AGENTS.md" "$abs/AGENTS.md"
      cp "$SRC/dist/CLAUDE.md" "$abs/CLAUDE.md"
      echo "  parent: AGENTS.md + CLAUDE.md"
    else
      echo "  warning: AGENTS.md/CLAUDE.md not found in $SRC/dist; run tools/build.py first" >&2
    fi
  fi
done

if [ "$codex_config" -eq 1 ]; then
  first="$(expand_tilde "${targets[0]}")"
  mkdir -p "$first"
  first="$(cd "$first" && pwd)"
  echo ""
  echo "# --- paste into ~/.codex/config.toml ---"
  for name in "${skill_arr[@]}"; do
    echo "[[skills.config]]"
    echo "path = \"$first/skills/$name/SKILL.md\""
    echo "enabled = true"
    echo ""
  done
fi

if [ "$dry_run" -eq 0 ] && [ "$with_parent" -eq 0 ]; then
  echo ""
  echo "Note: skills reference a parent prompt (<honesty_contract>,"
  echo "<language_policy>, <work_discipline>). Re-run with --with-parent to"
  echo "install AGENTS.md (and CLAUDE.md for Claude Code) into each target."
fi
