#!/usr/bin/env pwsh
<#
.SYNOPSIS
  Install the prompt skills into coding-agent skill directories.
.DESCRIPTION
  Each skill is installed as a SELF-CONTAINED unit. The skill's own files are
  copied under <target>/skills/<name>/, and the shared resources that skill
  actually references (shared/reference/*.md and, if any script is used, the
  whole shared/scripts/ set) are copied into <target>/skills/<name>/shared/.
  So a skill directory carries everything it needs and can be registered or
  moved on its own (GitHub Copilot, opencode, Claude Code; OpenAI Codex via
  -CodexConfig). No top-level shared/ tree is created.

  Every shared/ reference in the installed skill (with or without a leading
  ../../) is rewritten to an ABSOLUTE path under that skill's own shared/, so
  it resolves regardless of the agent's working directory. Absolute paths are
  deliberate: weak models resolve them reliably where a relative path is
  ambiguous.

  With -WithParent, the prebuilt AGENTS.md and CLAUDE.md (generated by build.py
  from the shared invariants) are copied into each target root so the
  <honesty_contract> / <language_policy> / <work_discipline> the skills assume
  are actually present.
.PARAMETER target
  Target root(s) to install into. Default: ~/.agents and ~/.claude
.PARAMETER with-parent
  Also install AGENTS.md + CLAUDE.md into each target root.
.PARAMETER dry-run
  Print actions without writing.
.PARAMETER codex-config
  Print the [[skills.config]] block for ~/.codex/config.toml (first target).
.EXAMPLE
  ./skills.ps1 --with-parent
.EXAMPLE
  ./skills.ps1 --target ~/.codex --codex-config
.NOTES
  Flags use the same --xxx-yyy form as skills.sh. PowerShell accepts both single
  and double dash, so --with-parent and -with-parent both work.
#>
[CmdletBinding()]
param(
  [string[]]${target},
  [switch]${with-parent},
  [switch]${dry-run},
  [switch]${codex-config}
)

$ErrorActionPreference = 'Stop'
# This script lives at <repo>/bootstrap/. The agents subsystem (skills/, shared/,
# and the generated parent files in dist/) is the sibling <repo>/agents/.
# bootstrap/install.ps1 delegates here; also runnable on its own.
$src = Join-Path (Split-Path $PSScriptRoot -Parent) 'agents'
$distSrc = Join-Path $src 'dist'
$skillsSrc = Join-Path $src 'skills'
$sharedSrc = Join-Path $src 'shared'
if (-not (Test-Path $skillsSrc) -or -not (Test-Path $sharedSrc)) {
  Write-Error "expected $skillsSrc and $sharedSrc to exist"
}

if (-not ${target} -or ${target}.Count -eq 0) {
  ${target} = @((Join-Path $HOME '.agents'), (Join-Path $HOME '.claude'))
}

$excludeDirs = @('__pycache__', '.pytest_cache', 'tests')
$utf8 = [System.Text.UTF8Encoding]::new($false)

function Expand-TargetPath([string]$p) {
  if ($p -like '~*') { $p = Join-Path $HOME ($p.Substring(1).TrimStart('/', '\')) }
  return [System.IO.Path]::GetFullPath($p)
}

function Copy-Tree([string]$from, [string]$to) {
  $base = (Resolve-Path $from).Path
  Get-ChildItem $base -Recurse -File | Where-Object {
    $rel = $_.FullName.Substring($base.Length)
    $parts = $rel.Split([char[]]@('/', '\'), [StringSplitOptions]::RemoveEmptyEntries)
    (-not ($parts | Where-Object { $excludeDirs -contains $_ })) -and ($_.Extension -ne '.pyc')
  } | ForEach-Object {
    $rel = $_.FullName.Substring($base.Length).TrimStart('/', '\')
    $dest = Join-Path $to $rel
    New-Item -ItemType Directory -Force -Path (Split-Path -Parent $dest) | Out-Null
    Copy-Item -LiteralPath $_.FullName -Destination $dest -Force
  }
}

function Install-Skill([string]$name, [string]$abs) {
  $skSrc = Join-Path $skillsSrc $name
  $dest = Join-Path (Join-Path $abs 'skills') $name
  Copy-Tree $skSrc $dest

  # Decide which shared resources this skill needs, by scanning its markdown.
  $mdFiles = Get-ChildItem $dest -Recurse -Filter '*.md'
  $needScripts = $false
  $needAllRefs = $false
  $refFiles = New-Object System.Collections.Generic.HashSet[string]
  foreach ($md in $mdFiles) {
    $text = [System.IO.File]::ReadAllText($md.FullName)
    if ($text -match 'shared/scripts/') { $needScripts = $true }
    # A placeholder reference (e.g. shared/reference/<language>.md) means the
    # skill picks the file at runtime, so it needs the whole reference set.
    if ($text -match 'shared/reference/<') { $needAllRefs = $true }
    foreach ($m in [regex]::Matches($text, 'shared/reference/([A-Za-z0-9_-]+\.md)')) {
      [void]$refFiles.Add($m.Groups[1].Value)
    }
  }

  # Copy the referenced shared/reference files (or all, for placeholders).
  $refDst = Join-Path (Join-Path $dest 'shared') 'reference'
  if ($needAllRefs) {
    New-Item -ItemType Directory -Force -Path $refDst | Out-Null
    Get-ChildItem (Join-Path $sharedSrc 'reference') -Filter '*.md' |
      ForEach-Object { Copy-Item -LiteralPath $_.FullName -Destination $refDst -Force }
  }
  elseif ($refFiles.Count -gt 0) {
    New-Item -ItemType Directory -Force -Path $refDst | Out-Null
    foreach ($rf in $refFiles) {
      $rfSrc = Join-Path (Join-Path $sharedSrc 'reference') $rf
      if (Test-Path $rfSrc) { Copy-Item -LiteralPath $rfSrc -Destination (Join-Path $refDst $rf) -Force }
    }
  }
  # Scripts have internal dependencies (_common.py), so copy them as a set.
  if ($needScripts) {
    Copy-Tree (Join-Path $sharedSrc 'scripts') (Join-Path (Join-Path $dest 'shared') 'scripts')
  }

  # Rewrite every shared/ reference to an absolute path under this skill.
  # Double any '$' in the destination so .NET Regex.Replace does not treat it as
  # a group reference in the replacement string (a path with '$' would corrupt).
  $destFwd = $dest -replace '\\', '/'
  $destFwdEsc = $destFwd.Replace('$', '$$')
  $rewritten = 0
  foreach ($md in (Get-ChildItem $dest -Recurse -Filter '*.md')) {
    $orig = [System.IO.File]::ReadAllText($md.FullName)
    $new = [regex]::Replace($orig, '(\.\./)*shared/(reference|scripts)/', "$destFwdEsc/shared/`$2/")
    if ($new -ne $orig) {
      [System.IO.File]::WriteAllText($md.FullName, $new, $utf8)
      $rewritten++
    }
  }
  Write-Host "  $name (rewrote $rewritten md files)"
}

$skillNames = Get-ChildItem $skillsSrc -Directory |
  Where-Object { Test-Path (Join-Path $_.FullName 'SKILL.md') } |
  Select-Object -ExpandProperty Name | Sort-Object

foreach ($t in ${target}) {
  $abs = Expand-TargetPath $t
  if (${dry-run}) {
    Write-Host "[dry-run] would install self-contained skills -> $abs/skills/<name>/"
    Write-Host "[dry-run]   skills: $($skillNames -join ', ')"
    Write-Host "[dry-run]   each gets only the shared/ refs it uses, rewritten to absolute"
    if (${with-parent}) { Write-Host "[dry-run]   plus AGENTS.md + CLAUDE.md -> $abs/" }
    continue
  }
  New-Item -ItemType Directory -Force -Path $abs | Out-Null
  Write-Host "installing -> $abs"
  foreach ($name in $skillNames) {
    Install-Skill $name $abs
  }
  if (${with-parent}) {
    $agentsSrc = Join-Path $distSrc 'AGENTS.md'
    $claudeSrc = Join-Path $distSrc 'CLAUDE.md'
    if ((Test-Path $agentsSrc) -and (Test-Path $claudeSrc)) {
      Copy-Item -LiteralPath $agentsSrc -Destination (Join-Path $abs 'AGENTS.md') -Force
      Copy-Item -LiteralPath $claudeSrc -Destination (Join-Path $abs 'CLAUDE.md') -Force
      Write-Host "  parent: AGENTS.md + CLAUDE.md"
    }
    else {
      Write-Warning "AGENTS.md/CLAUDE.md not found in $distSrc; run tools/build.py first"
    }
  }
}

if (${codex-config}) {
  $first = (Expand-TargetPath ${target}[0]) -replace '\\', '/'
  Write-Host ""
  Write-Host "# --- paste into ~/.codex/config.toml ---"
  foreach ($name in $skillNames) {
    Write-Host "[[skills.config]]"
    Write-Host "path = `"$first/skills/$name/SKILL.md`""
    Write-Host "enabled = true"
    Write-Host ""
  }
}

if (-not ${dry-run} -and -not ${with-parent}) {
  Write-Host ""
  Write-Host "Note: skills reference a parent prompt (<honesty_contract>, <language_policy>, <work_discipline>). Re-run with -WithParent to install AGENTS.md (and CLAUDE.md for Claude Code) into each target."
}
